# Generated by Django 3.2.7 on 2021-09-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=70)),
                ('direccion', models.CharField(default='', max_length=70)),
                ('nit', models.CharField(default='', max_length=70)),
                ('telefono', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
