# Generated by Django 3.2.7 on 2021-09-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_de_la_empresa', models.CharField(default='', max_length=70)),
                ('Dirección', models.CharField(default='', max_length=70)),
                ('NIT', models.CharField(default='', max_length=70)),
                ('Teléfono', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
